[engine.render]
window_title = "Default Window Name"
antiAliasing = 16

[engine.render.camera]
create_default_camera = true
set_default_camera_as_main = true

[engine.render.opengl]
background_color = [0.245, 0.40, 0.65, 0.8]

[engine]
database = "public/data/engine.db"
