set(file_prefix "/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/"
)

## Engine Built-in

file(GLOB_RECURSE assets "${CMAKE_SOURCE_DIR}/assets/ENGINE_BUILTIN/*")

set(assets_buffer "#pragma once\n\n${file_prefix}\n")

foreach(asset ${assets})

get_filename_component(name ${asset} NAME_WE)

string(REPLACE "-" "_" name ${name})

string(TOUPPER ${name} name)

file(READ ${asset} asset_content)

string(REPLACE ";" "\;" asset_content "${asset_content}")

set(var_type "const char*")

string(APPEND assets_buffer "\nstatic ${var_type} ASSET_BUILTIN_${name} = R\"(${asset_content})\"\;\n")

endforeach()

file(WRITE "${CMAKE_SOURCE_DIR}/include/PrettyEngine/assets/builtin.hpp" ${assets_buffer})

## Engine Compiled

file(GLOB_RECURSE assets "${CMAKE_SOURCE_DIR}/assets/ENGINE_COMPILED/*")

set(assets_buffer "#pragma once\n\n${file_prefix}\n")

foreach(asset ${assets})

get_filename_component(name ${asset} NAME_WE)

string(REPLACE "-" "_" name ${name})

string(TOUPPER ${name} name)

file(READ ${asset} asset_content)

string(REPLACE ";" "\;" asset_content "${asset_content}")

set(var_type "unsigned char*")

string(APPEND assets_buffer "\nstatic ${var_type} ASSET_COMPILED_${name} = R\"(${asset_content})\"\;\n")

endforeach()

file(WRITE "${CMAKE_SOURCE_DIR}/include/PrettyEngine/assets/bin.hpp" ${assets_buffer})
