[entities.Empty]
name = 'AnyEntity'
object = 'Empty'

    [entities.Empty.components]

    [entities.Empty.serial]
    ObjectName = ''
    ObjectUnique = '8583f39e-fcbd-43b2-a6c4-46367a9f7158'

        [entities.Empty.serial.fields]

    [entities.Empty.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[entities.editorEntity]
name = 'Editor'
object = 'Editor'

    [entities.editorEntity.components.LocalizationEditor]
    ObjectName = 'LocalizationEditor'
    ObjectUnique = 'LocalizationEditor'

        [entities.editorEntity.components.LocalizationEditor.fields]

    [entities.editorEntity.components.Render]
    ObjectName = 'Render'
    ObjectUnique = 'Render'

        [entities.editorEntity.components.Render.fields]
        Mesh = [ 'PrettyEngine::Mesh', '' ]
        MeshGUID = [ 'std::string', 'a71ab2f6-640e-4ac1-ba60-64cc21633bde' ]
        ScreenObject = [ 'bool', 'false' ]
        SunLight = [ 'bool', 'false' ]
        TextureBase = [ 'std::string', 'cpp_logo.png' ]
        TextureBaseGUID = [ 'std::string', '54e240db-0b66-4360-b598-bc91f5b71a12' ]
        TextureNormal = [ 'std::string', '' ]
        TextureNormalGUID = [ 'std::string', '4a1bd1d5-ec7c-4967-890b-694f8e5f2324' ]
        TextureTransparency = [ 'std::string', '' ]
        TextureTransparencyGUID = [ 'std::string', '8c3b2244-5cbb-4c80-86f3-548ee2c2dc78' ]
        UseLight = [ 'bool', 'false' ]
        UseTexture = [ 'bool', 'true' ]
        UseTextureBase = [ 'bool', 'true' ]
        UseTextureNormal = [ 'bool', 'false' ]
        UseTextureTransparency = [ 'bool', 'false' ]
        UseTexure = [ 'bool', 'true' ]

    [entities.editorEntity.serial]
    ObjectName = ''
    ObjectUnique = '37e594c5-1be1-448c-92db-d470d98294e6'

        [entities.editorEntity.serial.fields]

    [entities.editorEntity.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 0.5, 0.5, 0.5 ]

[meta]
name = 'Editor'