[entities.Editor]
name = 'editorEntity'
object = 'Editor'

    [entities.Editor.components.627f67b2-c9a2-4e44-9e46-799c258f39d6]
    ObjectName = 'LocalizationEditor'
    ObjectUnique = '627f67b2-c9a2-4e44-9e46-799c258f39d6'

        [entities.Editor.components.627f67b2-c9a2-4e44-9e46-799c258f39d6.fields]

    [entities.Editor.components.BaseCharacterController]
    ObjectName = 'BaseCharacterController'
    ObjectUnique = 'BaseCharacterController'

        [entities.Editor.components.BaseCharacterController.fields]
        colliderName = [ 'std::string', 'Collider' ]
        speed = [ 'float', '10.000000' ]

    [entities.Editor.components.Collider]
    ObjectName = 'Physical'
    ObjectUnique = 'Collider'

        [entities.Editor.components.Collider.fields]
        Gravity = [ 'glm::vec3', '0.000000;0.000000;0.000000;' ]
        fixed = [ 'bool', 'false' ]
        layer = [ 'std::string', 'Default' ]
        mass = [ 'float', '1.000000' ]
        model = [ 'std::string', 'rect' ]
        name = [ 'std::string', '2e2b9d2e-1615-4d50-80eb-bb139cf77dbc' ]
        rigidbody = [ 'bool', 'true' ]

    [entities.Editor.components.Render]
    ObjectName = 'Render'
    ObjectUnique = 'Render'

        [entities.Editor.components.Render.fields]
        Color = [ 'glm::vec4', '1.000000;1.000000;1.000000;1.000000;' ]
        Mesh = [ 'PrettyEngine::Mesh', '' ]
        MeshGUID = [ 'std::string', 'a71ab2f6-640e-4ac1-ba60-64cc21633bde' ]
        ScreenObject = [ 'bool', 'false' ]
        SunLight = [ 'bool', 'false' ]
        TextureBase = [ 'std::string', 'cpp_logo.png' ]
        TextureNormal = [ 'std::string', '' ]
        TextureTransparency = [ 'std::string', '' ]
        UseLight = [ 'bool', 'true' ]
        UseTexture = [ 'bool', 'true' ]
        UseTextureBase = [ 'bool', 'true' ]
        UseTextureNormal = [ 'bool', 'false' ]
        UseTextureTransparency = [ 'bool', 'false' ]
        UseTexure = [ 'bool', 'false' ]
        WireFrame = [ 'bool', 'false' ]

    [entities.Editor.serial]
    ObjectName = 'Editor'
    ObjectUnique = 'Editor'

        [entities.Editor.serial.fields]
        'Camera Speed' = [ 'f', '10.000000' ]

    [entities.Editor.transform]
    position = [ -0.34460815787315369, -0.48629587888717651, 0.0 ]
    rotation = [ -0.0, 0.0, 1.0, -4.3711388286737929e-08 ]
    scale = [ 0.5, 0.5, 0.5 ]

[entities.Empty]
name = 'AnyEntity'
object = 'Empty'

    [entities.Empty.components.Light]
    ObjectName = 'Light'
    ObjectUnique = 'Light'

        [entities.Empty.components.Light.fields]
        Color = [ 'glm::vec3', '1.000000;1.000000;1.000000;' ]
        DeferredFactor = [ 'float', '1.000000' ]
        LightFactor = [ 'float', '2.000000' ]
        LightLayer = [ 'int', '0' ]
        Radius = [ 'float', '5.000000' ]
        SpotDirection = [ 'glm::vec4', '0.000000;0.000000;0.000000;0.000000;' ]
        SpotLightCutOff = [ 'float', '0.000000' ]
        Type = [ 'PrettyEngine::LightType', 'point' ]

    [entities.Empty.components.Physical]
    ObjectName = 'Physical'
    ObjectUnique = 'Physical'

        [entities.Empty.components.Physical.fields]
        Gravity = [ 'glm::vec3', '0.000000;9.810000;0.000000;' ]
        fixed = [ 'bool', 'true' ]
        layer = [ 'std::string', 'Default' ]
        mass = [ 'float', '1.000000' ]
        model = [ 'std::string', 'rect' ]
        name = [ 'std::string', 'a14230b8-a675-4ac6-9517-5de9aed3df92' ]
        rigidbody = [ 'bool', 'true' ]

    [entities.Empty.components.Render]
    ObjectName = 'Render'
    ObjectUnique = 'Render'

        [entities.Empty.components.Render.fields]
        Color = [ 'glm::vec4', '1.000000;0.000000;0.000000;1.000000;' ]
        Mesh = [ 'PrettyEngine::Mesh', '' ]
        MeshGUID = [ 'std::string', '95ed72d6-f6f0-49b1-a556-7ab04903c634' ]
        ScreenObject = [ 'bool', 'false' ]
        SunLight = [ 'bool', 'false' ]
        TextureBase = [ 'std::string', '' ]
        TextureNormal = [ 'std::string', '' ]
        TextureTransparency = [ 'std::string', '' ]
        UseLight = [ 'bool', 'false' ]
        UseTextureBase = [ 'bool', 'false' ]
        UseTextureNormal = [ 'bool', 'false' ]
        UseTextureTransparency = [ 'bool', 'false' ]
        UseTexure = [ 'bool', 'false' ]
        WireFrame = [ 'bool', 'true' ]

    [entities.Empty.serial]
    ObjectName = 'Empty'
    ObjectUnique = 'Empty'

        [entities.Empty.serial.fields]

    [entities.Empty.transform]
    position = [ 1.0, 0.0, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 1.0, 1.0, 0.5 ]

[meta]
name = 'Editor'