[meta]
name = "World"

[render]
[visualObjectA]
position = [0, 0, 0]
rotation = [0, 0, 0]
size = [1, 1, 1]

texture = "SampleA"

color = [1, 1, 1]
opacity = 1.0

[entities]
[entities.entityA]
type = "Entity"
object = "Editor"
[entities.entityA.transform]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 0.0]
size = [1.0, 1.0, 1.0]

[entities.entityA.public.publicA]
type = "str"
content = "Hell, World!"

[components]