[entities.editorEntity]
components = [ [ 'LocalizationEditor', 'LocalizationEditor' ] ]
name = 'Editor'
object = 'Editor'
public_map = []

    [entities.editorEntity.transform]
    position = [ 0.64004707336425781, 1.0, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 0.5, 0.5, 0.5 ]

[meta]
name = 'Editor'