[entities.editorEntity]
name = 'Editor'
object = 'Editor'

    [entities.editorEntity.components.LocalizationEditor]
    ObjectName = 'LocalizationEditor'
    ObjectUnique = 'LocalizationEditor'

        [entities.editorEntity.components.LocalizationEditor.fields]

    [entities.editorEntity.components.Render]
    ObjectName = 'Render'
    ObjectUnique = 'Render'

        [entities.editorEntity.components.Render.fields]
        Mesh = [ 'PrettyEngine::Mesh', '' ]
        MeshGUID = [ 'std::string', 'a71ab2f6-640e-4ac1-ba60-64cc21633bde' ]
        ScreenObject = [ 'bool', 'false' ]
        SunLight = [ 'bool', 'false' ]
        TextureBase = [ 'std::string', '' ]
        TextureBaseGUID = [ 'std::string', '54e240db-0b66-4360-b598-bc91f5b71a12' ]
        TextureNormal = [ 'std::string', '' ]
        TextureNormalGUID = [ 'std::string', '4a1bd1d5-ec7c-4967-890b-694f8e5f2324' ]
        TextureTransparency = [ 'std::string', '' ]
        TextureTransparencyGUID = [ 'std::string', '8c3b2244-5cbb-4c80-86f3-548ee2c2dc78' ]
        UseLight = [ 'bool', 'false' ]
        UseTexture = [ 'bool', 'false' ]
        UseTextureBase = [ 'bool', 'false' ]
        UseTextureNormal = [ 'bool', 'false' ]
        UseTextureTransparency = [ 'bool', 'false' ]
        UseTexure = [ 'bool', 'false' ]

    [entities.editorEntity.serial]
    ObjectName = ''
    ObjectUnique = '7ccab998-7203-433d-8c79-c5fa4e4a1469'

        [entities.editorEntity.serial.fields]

    [entities.editorEntity.transform]
    position = [ -0.8076468110084534, 0.4743005633354187, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 0.5, 0.5, 0.5 ]

[meta]
name = 'Editor'