[entities.entityA]
components = [
    [ 'LocalizationEditor', 'LocalizationEditor' ],
    [ 'Render', 'Render', 'Texture Base', 'image.png', 'Mesh', 'rect', 'UseLight', 'true', 'SunLight', 'false' ],
    [
        'Light',
        'Light',
        'LightLayer',
        '0',
        'LightFactor',
        '2.0',
        'Color',
        '1;1;1;1;',
        'Type',
        '',
        'DeferredFactor',
        '1.0',
        'Radius',
        '5.0',
        'SpotDirection',
        '',
        'SpotLightCutOff',
        ''
    ]
]
name = 'Editor'
object = 'Editor'
public_map = [ [ 'projectName', 'MyNewProject' ] ]

    [entities.entityA.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, 0.0, 0.0, 0.0 ]
    scale = [ 0.5, 0.5, 0.5 ]

[meta]
name = 'World'