[entities.editorEntity]
name = 'Editor'
object = 'Editor'

    [entities.editorEntity.components.LocalizationEditor]
    ObjectName = 'LocalizationEditor'
    ObjectUnique = 'LocalizationEditor'

        [entities.editorEntity.components.LocalizationEditor.fields]

    [entities.editorEntity.components.Render]
    ObjectName = 'Render'
    ObjectUnique = 'Render'

        [entities.editorEntity.components.Render.fields]

    [entities.editorEntity.serial]
    ObjectName = ''
    ObjectUnique = '8ea771fa-9747-4943-bfb9-97fe73f4626f'

        [entities.editorEntity.serial.fields]

    [entities.editorEntity.transform]
    position = [ -0.8076468110084534, 0.4743005633354187, 0.0 ]
    rotation = [ 0.0, -0.0, 0.0, 1.0 ]
    scale = [ 0.5, 0.5, 0.5 ]

[meta]
name = 'Editor'