[meta]
name = "World"

[render]
[visualObjectA]
position = [0, 0, 0]
rotation = [0, 0, 0]
size = [1, 1, 1]

texture = "SampleA"

color = [1, 1, 1]
opacity = 1.0

[entities]
[entities.entityA]
name = "Editor"
type = "Entity"
object = "Editor"
components = [["LocalizationEditor", "LocalizationEditor"]]
public_map = [["projectName", "MyNewProject"]]

[entities.entityA.transform]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]
