[entities.otherCollider]
components = [
    [ 'Render', 'Render', 'Texture Base', 'c#.png', 'Mesh', 'rect', 'UseLight', 'false', 'SunLight', 'false' ],
    ['Physical', 'Physical']
]
name = 'PhysicalObject'
object = 'Empty'
public_map = [ [ 'projectName', 'MyNewProject' ] ]

    [entities.otherCollider.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[entities.entityA]
components = [
    [ 'LocalizationEditor', 'LocalizationEditor' ],
    [ 'Render', 'Render', 'Texture Base', 'cpp_logo.png', 'Mesh', 'rect', 'UseLight', 'true', 'SunLight', 'false' ],
    [
        'Light',
        'Light',
        'LightLayer',
        '0',
        'LightFactor',
        '2.0',
        'Color',
        '1;1;1;1;',
        'Type',
        '',
        'DeferredFactor',
        '1.0',
        'Radius',
        '5.0',
        'SpotDirection',
        '',
        'SpotLightCutOff',
        ''
    ],
    ['Physical', 'Physical']
]
name = 'Editor'
object = 'Editor'
public_map = [ [ 'projectName', 'MyNewProject' ] ]

    [entities.entityA.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, 0.0, -0.61097586154937744, 0.79164934158325195 ]
    scale = [ 1.0, 1.0, 1.0 ]

[meta]
name = 'World'