#pragma once

#include <Editor.hpp>
#include <Empty.hpp>

#include <PrettyEngine/entity.hpp>

#include <string>
#include <memory>

/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/

static std::shared_ptr<PrettyEngine::Entity> CreateCustomEntity(std::string name) {
    if(name == "Editor") {
        return std::make_shared<Custom::Editor>();
    }     if(name == "Empty") {
        return std::make_shared<Custom::Empty>();
    } 
 	return nullptr;
}