
#include <PrettyEngine/world.hpp>

#include <string>
#include <memory>

/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/

static void CreateCustomEntity(std::string name, std::shared_ptr<PrettyEngine::World> world) {
