#pragma once

#include <LocalizationEditor.hpp>
#include <Render.hpp>

#include <PrettyEngine/entity.hpp>
#include <PrettyEngine/world.hpp>

#include <string>
#include <memory>

/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/

static std::shared_ptr<PrettyEngine::Component> GetCustomComponent(std::string name) {
    if(name == "LocalizationEditor") {
        return std::make_shared<Custom::LocalizationEditor>();
    }     if(name == "Render") {
        return std::make_shared<Custom::Render>();
    } 
 return nullptr;
}