
#include <PrettyEngine/entity.hpp>

#include <string>
#include <memory>

/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/

static std::shared_ptr<PrettyEngine::Component> GetCustomComponent(std::string name) {
