#pragma once

#include <PrettyEngine/world.hpp>

/******************************************************
 * THIS FILE IS AUTO-GENERATED BY A CMAKE SCRIPT.    *
 *                                                   *
 * DO NOT MODIFY THIS FILE MANUALLY, AS IT WILL BE   *
 * REGENERATED AUTOMATICALLY UPON THE NEXT BUILD.    *
 ******************************************************/

#define CUSTOM "CUSTOM"